sensors:
  camera_rgb:
    type: boxu8
    high: 255
    low: 0
    shape: [480, 640, 3]
#  camera_depth:
#    type: boxu8
#    high: 255
#    low: 0
#    shape: [1280, 720, 4]

gazebo:
  sensors:
    camera_rgb:
      topic: camera/color/image_raw
      msg_name: Image
      type: data
#    camera_depth:
#      topic: camera/depth/image_rect_raw
#      msg_name: Image
#      type: data

real:
  sensors:
    camera_rgb:
      topic: /camera/color/image_raw
      msg_name: Image
      type: data
#    camera_depth:
#      topic: camera/depth/image_rect_raw
#      msg_name: Image
#      type: data

pybullet:
  xacro: $(find realsense2_description)/urdf/test_d435_camera.urdf.xacro
  xacro_args:
    use_nominal_extrinsics: 'true'
  urdf_name: realsense2_d435
  sensors:
    camera_rgb:
      # "realsense2_camera" --> ${name}_color_optical_frame
      type: camera_rgb
      optical_frame_link: camera_color_optical_frame
      intrinsic:
        fov: 57 # (deg)
        near_val: 0.1 # (m)
        far_val: 100 # (m)
      extrinsic:
        pos: [0, 0, 0.05] # (m)
        euler: [0, -45, 0]  # [roll, pitch, yaw] (deg)
        dist: 1.0 # (m)
        up_axis: 2

#    camera_depth:
#      type: camera_rgbd
#      intrinsic:
#        fov: 80.21 # (deg)
#        near_val: 0.1 # (m)
#        far_val: 100 # (m)
#      extrinsic:
#        pos: [0, 0, 0.05] # (m)
#        euler: [0, -45, 0]  # [roll, pitch, yaw] (deg)
#        dist: 1.0 # (m)
#        up_axis: 2
