sensors:
  joint_sensors:
    type: boxf32
    high: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    low: [-3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159]
#  gripper_sensor:
#    type: boxf32
#    high: [0.037, -0.015]
#    low: [0.015, -0.037]

actuators:
  joints:
    type: boxf32
    high: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    low: [-3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159]
  gripper:
    type: boxf32
    high: [0.037, -0.015]
    low: [0.015, -0.037]

states:
  joint_pos:
    type: boxf32
    high: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
    low: [-3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159]
  joint_vel:
    type: boxf32
    high: [1, 1, 1, 1, 1, 1]
    low: [-1, -1, -1, -1, -1, -1]

gazebo:
  sensors:
    joint_sensors:
      topic: vx300s/joint_states
      msg_name: JointState
      type: position
      entries: [6, 5, 0, 1, 7, 8]

  actuators:
    joints:
      server_name: vx300s/arm_controller/follow_joint_trajectory
      action_server: FollowJointTrajectoryActionServer
      names: [waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate]

  states: # IMPORTANT! Only add states you are able to both read and reset in the physics engine
    joint_pos:
      names:
      -
    joint_vel:
      names:
      -
