sensors:
  camera_right:
    type: boxu8
    high: 255
    low: 0
    shape: [544, 1024, 4]
  camera_left:
    type: boxu8
    high: 255
    low: 0
    shape: [544, 1024, 4]

webots:
  node_type_name: MultiSenseS21
  default_translation: [0, 0, 0]
  default_orientation: [0.5, -0.5, -0.5, 0.5]
  as_child: True
  sensors:
    camera_right:
      type: camera
      remap: True
      names:
        - MultiSense_S21_right_camera
    camera_left:
      type: camera
      names:
        - MultiSense_S21_left_camera

pybullet:
  xacro: $(find eager_sensor_multisense_s21)/urdf/multisense_s21.urdf.xacro
  urdf_name: multisense_s21
  sensors:
    camera_right:
      type: camera_rgbd
      optical_frame_link: right_camera_optical_frame
      names: [MultiSense_S21_right_camera]
      intrinsic:
        fov: 80.21 # (deg)
        near_val: 0.1 # (m)
        far_val: 100 # (m)
      extrinsic:
        pos: [0, 0, 0.05] # (m)
        euler: [0, -45, 0]  # [roll, pitch, yaw] (deg)
        dist: 1.0 # (m)
        up_axis: 2

    camera_left:
      type: camera_rgbd
      optical_frame_link: left_camera_optical_frame
      names: [MultiSense_S21_left_camera]
      intrinsic:
        fov: 80.21 # (deg)
        near_val: 0.1 # (m)
        far_val: 100 # (m)
      extrinsic:
        pos: [0, 0, 0.05] # (m)
        euler: [0, -45, 0]  # [roll, pitch, yaw] (deg)
        dist: 1.0 # (m)
        up_axis: 2
