#!/usr/bin/env python

import sys

from eager_demo_rqt.eager_demo_rqt import EagerDemoRqt
from rqt_gui.main import Main

plugin = 'eager_demo_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
