sensors:
  camera_right:
    type: boxu8
    high: 255
    low: 0
    shape: [1024, 544, 4]
  camera_left:
    type: boxu8
    high: 255
    low: 0
    shape: [1024, 544, 4]

webots:
  sensors:
    camera_right:
      type: camera
      names:
        - MultiSense_S21_right_camera
    camera_left:
      type: camera
      names:
        - MultiSense_S21_left_camera

pybullet:
  urdf:
  sensors:
    camera_right:
      type: camera_rgbd
      names: [MultiSense_S21_right_camera]
      intrinsic:
        fov: 80.21 # (deg)
        near_val: 0.1 # (m)
        far_val: 100 # (m)
      extrinsic:
        pos: [0.5, 0.1, 0] # (m)
        euler: [90, -25, 0]  # [yaw, pitch, roll] (deg)
        dist: 0.7 # (m)
        up_axis: 2

    camera_left:
      type: camera_rgbd
      names: [MultiSense_S21_left_camera]
      intrinsic:
        fov: 80.21 # (deg)
        near_val: 0.1 # (m)
        far_val: 100 # (m)
      extrinsic:
        pos: [0.5, -0.1, 0] # (m)
        euler: [0, -25, 90]  # [roll, pitch, yaw] (deg)
        dist: 0.7 # (m)
        up_axis: 2