sensors:
  camera_right:
    type: boxu8
    high: 255
    low: 0
    shape: [2228224]
  camera_left:
    type: boxu8
    high: 255
    low: 0
    shape: [2228224]

webots:
  sensors:
    camera_right:
      type: camera
      names:
        - MultiSense_S21_right_camera
    camera_left:
      type: camera
      names:
        - MultiSense_S21_left_camera
